# Generated by Django 3.1.5 on 2021-02-02 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.BigIntegerField(default=2347000000),
        ),
    ]
