# Generated by Django 3.1.5 on 2021-02-05 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_remove_patient_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='verification',
        ),
        migrations.AddField(
            model_name='patient',
            name='phone_number',
            field=models.BigIntegerField(blank=True, default=234),
        ),
    ]
