# Generated by Django 3.1.5 on 2021-02-05 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_auto_20210205_1907'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='verification',
            field=models.CharField(default='osun', max_length=200),
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.BigIntegerField(),
        ),
    ]
