# Generated by Django 3.1.5 on 2021-02-05 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_auto_20210205_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.CharField(blank=True, default=90, max_length=200),
        ),
    ]
