# Generated by Django 3.1.5 on 2021-02-05 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0011_auto_20210205_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_number',
            field=models.BigIntegerField(blank=True, default=2347000000),
        ),
    ]
