# Generated by Django 3.1.5 on 2021-02-13 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0012_auto_20210205_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], default='Male', max_length=100),
        ),
    ]
