# Generated by Django 3.1.5 on 2021-04-08 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0013_patient_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='extra_field',
            field=models.CharField(choices=[('Negative', 'Negative'), ('Positive', 'Positive'), ('Awaiting', 'Awaiting')], default='Awaiting', max_length=100),
        ),
    ]
